defaults:
  - group1: ???
  - group2: ???

  - _self_

hydra:
  run:
    dir: results/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: results/hydra/${hydra.job.name}_sweep/${now:%Y-%m-%d_%H-%M-%S}

wandb:
  project: sweep-test
  entity: yp-edu
  mode: offline
